// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Tanulok_proba.Data;

#nullable disable

namespace Tanulok_proba.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20220512091055_Init")]
    partial class Init
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("Tanulok_proba.Model.Diak", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Nev")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Diakok");
                });

            modelBuilder.Entity("Tanulok_proba.Model.Tanar", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Nev")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Tanarok");
                });

            modelBuilder.Entity("Tanulok_proba.Model.TanarDiak", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<int>("DiakId")
                        .HasColumnType("int");

                    b.Property<int>("TanarId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("DiakId");

                    b.HasIndex("TanarId");

                    b.ToTable("TanarDiak");
                });

            modelBuilder.Entity("Tanulok_proba.Model.TanarDiak", b =>
                {
                    b.HasOne("Tanulok_proba.Model.Diak", "Diak")
                        .WithMany("TanarDiak")
                        .HasForeignKey("DiakId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Tanulok_proba.Model.Tanar", "Tanar")
                        .WithMany("TanarDiak")
                        .HasForeignKey("TanarId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Diak");

                    b.Navigation("Tanar");
                });

            modelBuilder.Entity("Tanulok_proba.Model.Diak", b =>
                {
                    b.Navigation("TanarDiak");
                });

            modelBuilder.Entity("Tanulok_proba.Model.Tanar", b =>
                {
                    b.Navigation("TanarDiak");
                });
#pragma warning restore 612, 618
        }
    }
}
